const sessions = [
  {
    subjectRef: 'IP',
    subjectCodeRef: 'IT1023',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    roomRef: 'A502',
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Janith Gamage']
  },
  {
    subjectRef: 'ICS',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Janith Gamage'],
    roomRef: 'N3E'

  },
  {
    subjectRef: 'CS',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Wednesday',
    lecturers:['Janith Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'OOC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Friday',
    lecturers:['Janith Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'ISDM',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Wednesday',
    lecturers:['Janith Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'ESD',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Roshan Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'ESD',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Friday',
    lecturers:['Roshan Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'SA',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Roshan Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'SA',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Wednesday',
    lecturers:['Roshan Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'UEE',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Roshan Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'UEE',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Friday',
    lecturers:['Kavindu Gamage'],
    roomRef: 'Auditorium'
  },
  {
    subjectRef: 'UEE',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kavindu Gamage'],
    roomRef: 'Auditorium'
  },
  {
    subjectRef: 'DBS',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kavindu Gamage'],
    roomRef: 'Auditorium'
  },
  {
    subjectRef: 'DBS',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Wednesday',
    lecturers:['Kavindu Gamage'],
    roomRef: 'Auditorium'
  },
  {
    subjectRef: 'DBS',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(SE)',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Friday',
    lecturers:['Janaka Gamage'],
    roomRef: 'Auditorium'
  },
  {
    subjectRef: 'CSSE',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(SE)',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Janaka Gamage'],
    roomRef: 'Auditorium'
  },
  {
    subjectRef: 'CSSE',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(SE)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Friday',
    lecturers:['Janaka Gamage'],
    roomRef: 'D301'
  },
  {
    subjectRef: 'CSSE',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(SE)',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Janaka Gamage'],
    roomRef: 'D301'
  },
  {
    subjectRef: 'AF',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(SE)',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Friday',
    lecturers:['Janaka Gamage'],
    roomRef: 'D301'
  },
  {
    subjectRef: 'AF',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(SE)',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Janaka Gamage'],
    roomRef: 'D301'
  },
  {
    subjectRef: 'PS',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(SE)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Thursday',
    lecturers:['Janaka Gamage'],
    roomRef: 'D301'
  },
  {
    subjectRef: 'AF',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(SE)',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Janaka Gamage'],
    roomRef: 'D301'
  },
  {
    subjectRef: 'PS',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Thursday',
    lecturers:['Janaka Gamage'],
    roomRef: 'D301'
  },
  {
    subjectRef: 'PS',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Janaka Gamage'],
    roomRef: 'D301'
  },
  {
    subjectRef: 'MAD',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Janaka Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'MAD',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Thursday',
    lecturers:['Kodagoda'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'MAD',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kasun Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'ITP',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Kasun Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'DMS',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y2.S2.02(IT)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Kasun Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'DMS',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Janith Gamage'],
    roomRef: 'A502'
  },
  {
    subjectRef: 'DMS',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Janith Gamage'],
    roomRef: 'N3E'
  },
  {
    subjectRef: 'IWT',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Janith Gamage'],
    roomRef: 'N3E'
  },
  {
    subjectRef: 'IWT',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Janith Gamage'],
    roomRef: 'N3E'
  },
  {
    subjectRef: 'SPM',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Janith Gamage'],
    roomRef: 'B405-Pclab'
  },
  {
    subjectRef: 'EAP',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Janith Gamage'],
    roomRef: 'B405-Pclab'
  },
  {
    subjectRef: 'SPM',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Wednesday',
    lecturers:['Janith Gamage'],
    roomRef: 'N3E'
  },
  {
    subjectRef: 'OOC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Janith Gamage'],
    roomRef: 'B405-Pclab'
  },
  {
    subjectRef: 'EAP',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '10:30',
    endTime: '12:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Janith Gamage'],
    roomRef: 'N3E'
  },
  {
    subjectRef: 'OOC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '13:30',
    endTime: '15:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Monday',
    lecturers:['Janith Gamage'],
    roomRef: 'B405-Pclab'
  },
  {
    subjectRef: 'OOC',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '15:30',
    endTime: '17:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Janith Gamage'],
    roomRef: 'N3E'
  },
  {
    subjectRef: 'ISDM',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Thursday',
    lecturers:['Janith Gamage'],
    roomRef: 'B405-Pclab'
  },
  {
    subjectRef: 'OOC',
    subjectCodeRef: '1070B',
    tagRef: 'Practical',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Tuesday',
    lecturers:['Janith Gamage'],
    roomRef: 'N3E'
  },
  {
    subjectRef: 'ISDM',
    subjectCodeRef: '1070B',
    tagRef: 'Lecture',
    groupRef: 'Y4.S2.02(SE)',
    subGroupRef: null,
    startTime: '08:30',
    endTime: '10:30',
    isParallel: false,
    parallelId: null,
    isConsecutive: false,
    consecutiveId: null,
    isSameRoom: false,
    studentCount: 60,
    duration: '2',
    day: 'Wednesday',
    lecturers:['Janith Gamage'],
    roomRef: 'N3E'
  },

];

export default sessions;
